package Polypro;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import helper.Auth;
import helper.MgsBox;
import helper.XDate;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.Timer;

/**
 *
 * @author Sieu Nhan Bay
 */
public class formCha extends javax.swing.JFrame {

    /**
     * Creates new form formCha
     */
      Thread dongho;
     public void loaddh(){
        dongho=new Thread(){
             @Override
        public void run() {
                 while (true) {
                 Date d=new Date();
                     SimpleDateFormat day=new SimpleDateFormat("hh:mm:ss");
                     Date time=XDate.now();
                     lblDongHo.setText(XDate.toString(time));
                     try {
                         Thread.sleep(1000);
                     } catch (InterruptedException ex) {
                         break;
                     }   
                 }
        }    
        };
        dongho.start();
     }
    public formCha() {
        initComponents();
        init();
        startDongHo();
        
    }
    
    void init(){
        this.openWellcome();
        this.dangNhap();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnKetthuc = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnChuyende = new javax.swing.JButton();
        btnKhoahoc = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnHocvien = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnHuongdan = new javax.swing.JButton();
        jdesktop = new javax.swing.JDesktopPane(){
            protected void  paintComponent (Graphics g){
                Image img = new ImageIcon(this.getClass().getResource("/icon/logo.png")).getImage();
                try {
                    Graphics g2d = (Graphics2D)g;
                    double x= img.getWidth(null);
                    double y= img.getHeight(null);
                    //g2d.scale(getWidth()/x,getHeight()/y);
                    //g2d.drawImage(img, 0, 0, this);
                    g2d.drawImage(img, this.getWidth()/4+100,this.getHeight()/4-100,this);
                } catch (Exception e) {
                    System.out.println("Gap loi");
                }
            }
        };
        jPanel1 = new javax.swing.JPanel();
        lbltrangthai = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mniDangNhap = new javax.swing.JMenu();
        mnidangnhap = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnidoimk = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniketthuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniNguoihoc = new javax.swing.JMenuItem();
        mniChuyende = new javax.swing.JMenuItem();
        Mnikhoahoc = new javax.swing.JMenuItem();
        mnihocvien = new javax.swing.JMenuItem();
        mniNhanvien = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniluongnguoihoc = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniBangDiem = new javax.swing.JMenuItem();
        mniDiemchuyende = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        MniDoanhthu = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnihuongdan = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniGioithieu = new javax.swing.JMenuItem();

        jMenuItem15.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Funny.png"))); // NOI18N
        jMenuItem15.setText("CHÚC BẠN HỌC TẬP TỐT");
        jMenuItem15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        popupMenu.add(jMenuItem15);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png")).getImage());

        btnDangXuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setMargin(new java.awt.Insets(12, 30, 12, 30));
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);

        btnKetthuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKetthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
        btnKetthuc.setText("Kết thúc");
        btnKetthuc.setFocusable(false);
        btnKetthuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetthuc.setMargin(new java.awt.Insets(12, 30, 12, 30));
        btnKetthuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetthucActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKetthuc);
        jToolBar1.add(jSeparator7);

        btnChuyende.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lists.png"))); // NOI18N
        btnChuyende.setText("Chuyên đề");
        btnChuyende.setFocusable(false);
        btnChuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyende.setMargin(new java.awt.Insets(12, 30, 12, 30));
        btnChuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyendeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChuyende);

        btnKhoahoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Certificate.png"))); // NOI18N
        btnKhoahoc.setText("Khóa học");
        btnKhoahoc.setFocusable(false);
        btnKhoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoahoc.setMargin(new java.awt.Insets(12, 30, 12, 30));
        btnKhoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoahocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhoahoc);

        btnNguoiHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Conference.png"))); // NOI18N
        btnNguoiHoc.setText("Người học");
        btnNguoiHoc.setFocusable(false);
        btnNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoiHoc.setMargin(new java.awt.Insets(12, 30, 12, 30));
        btnNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNguoiHoc);

        btnHocvien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N
        btnHocvien.setText("Học viên");
        btnHocvien.setFocusable(false);
        btnHocvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHocvien.setMargin(new java.awt.Insets(12, 30, 12, 30));
        btnHocvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHocvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocvienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHocvien);
        jToolBar1.add(jSeparator6);

        btnHuongdan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Globe.png"))); // NOI18N
        btnHuongdan.setText("Hướng dẫn");
        btnHuongdan.setFocusable(false);
        btnHuongdan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongdan.setMargin(new java.awt.Insets(12, 30, 12, 30));
        btnHuongdan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongdanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHuongdan);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jdesktop.setBackground(new java.awt.Color(157, 189, 228));
        jdesktop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jdesktopMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jdesktopLayout = new javax.swing.GroupLayout(jdesktop);
        jdesktop.setLayout(jdesktopLayout);
        jdesktopLayout.setHorizontalGroup(
            jdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1169, Short.MAX_VALUE)
        );
        jdesktopLayout.setVerticalGroup(
            jdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        getContentPane().add(jdesktop, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        lbltrangthai.setForeground(new java.awt.Color(51, 51, 255));
        lbltrangthai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Info.png"))); // NOI18N
        lbltrangthai.setText("Hệ quản lý đào tạo");
        jPanel1.add(lbltrangthai, java.awt.BorderLayout.CENTER);

        lblDongHo.setForeground(new java.awt.Color(0, 51, 255));
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Alarm.png"))); // NOI18N
        lblDongHo.setText("10:55 PM");
        jPanel1.add(lblDongHo, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        mniDangNhap.setText("Hệ thống");
        mniDangNhap.setMargin(new java.awt.Insets(5, 5, 5, 5));

        mnidangnhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnidangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Key.png"))); // NOI18N
        mnidangnhap.setText("Đăng nhập");
        mnidangnhap.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnidangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangnhapActionPerformed(evt);
            }
        });
        mniDangNhap.add(mnidangnhap);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Log out.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mniDangNhap.add(mniDangXuat);
        mniDangNhap.add(jSeparator1);

        mnidoimk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        mnidoimk.setText("Đổi mật khẩu");
        mnidoimk.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnidoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidoimkActionPerformed(evt);
            }
        });
        mniDangNhap.add(mnidoimk);
        mniDangNhap.add(jSeparator2);

        mniketthuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
        mniketthuc.setText("Kết thúc");
        mniketthuc.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniketthucActionPerformed(evt);
            }
        });
        mniDangNhap.add(mniketthuc);

        jMenuBar1.add(mniDangNhap);

        jMenu2.setText("Quản lý");
        jMenu2.setMargin(new java.awt.Insets(5, 5, 5, 5));

        mniNguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Conference.png"))); // NOI18N
        mniNguoihoc.setText("Người học");
        mniNguoihoc.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniNguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNguoihocActionPerformed(evt);
            }
        });
        jMenu2.add(mniNguoihoc);

        mniChuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniChuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lists.png"))); // NOI18N
        mniChuyende.setText("Chuyên đề");
        mniChuyende.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniChuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChuyendeActionPerformed(evt);
            }
        });
        jMenu2.add(mniChuyende);

        Mnikhoahoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Mnikhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Certificate.png"))); // NOI18N
        Mnikhoahoc.setText("Khóa học");
        Mnikhoahoc.setMargin(new java.awt.Insets(5, 5, 5, 5));
        Mnikhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnikhoahocActionPerformed(evt);
            }
        });
        jMenu2.add(Mnikhoahoc);

        mnihocvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnihocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N
        mnihocvien.setText("Học viên");
        mnihocvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnihocvienActionPerformed(evt);
            }
        });
        jMenu2.add(mnihocvien);

        mniNhanvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User group.png"))); // NOI18N
        mniNhanvien.setText("Quản lý nhân viên");
        mniNhanvien.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanvienActionPerformed(evt);
            }
        });
        jMenu2.add(mniNhanvien);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Thống kê");
        jMenu4.setMargin(new java.awt.Insets(5, 5, 5, 5));

        mniluongnguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniluongnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clien list.png"))); // NOI18N
        mniluongnguoihoc.setText("Người học tùng năm");
        mniluongnguoihoc.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniluongnguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniluongnguoihocActionPerformed(evt);
            }
        });
        jMenu4.add(mniluongnguoihoc);
        jMenu4.add(jSeparator3);

        mniBangDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Card file.png"))); // NOI18N
        mniBangDiem.setText("Bảng điểm khóa");
        mniBangDiem.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBangDiemActionPerformed(evt);
            }
        });
        jMenu4.add(mniBangDiem);

        mniDiemchuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniDiemchuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Bar chart.png"))); // NOI18N
        mniDiemchuyende.setText("Điểm từng khóa học");
        mniDiemchuyende.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniDiemchuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiemchuyendeActionPerformed(evt);
            }
        });
        jMenu4.add(mniDiemchuyende);
        jMenu4.add(jSeparator4);

        MniDoanhthu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MniDoanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dollar.png"))); // NOI18N
        MniDoanhthu.setText("Doanh thu từng chuyên đề");
        MniDoanhthu.setMargin(new java.awt.Insets(5, 5, 5, 5));
        MniDoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniDoanhthuActionPerformed(evt);
            }
        });
        jMenu4.add(MniDoanhthu);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Trợ giúp");
        jMenu6.setMargin(new java.awt.Insets(5, 5, 5, 5));

        mnihuongdan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnihuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Globe.png"))); // NOI18N
        mnihuongdan.setText("Hướng dẫn sử dụng");
        mnihuongdan.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnihuongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnihuongdanActionPerformed(evt);
            }
        });
        jMenu6.add(mnihuongdan);
        jMenu6.add(jSeparator5);

        mniGioithieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mniGioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Brick house.png"))); // NOI18N
        mniGioithieu.setText("Giới thiệu sản phẩm");
        mniGioithieu.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniGioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioithieuActionPerformed(evt);
            }
        });
        jMenu6.add(mniGioithieu);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void openWellcome(){
        new ChaoJDialog(this,true).setVisible(true);
        
    }
   void startDongHo(){
        loaddh();
    }
    void openDoiMatKhau(){
        if (Auth.isLogin()) {
            new doiMatKhauJDialog(this,true).setVisible(true);
        }
        else{
            MgsBox.alert(this,"Vui lòng Đăng nhập!");
        }
    }
    void dangNhap(){
        new dangNhapJDialog(this,true).setVisible(true);
    }
    void dangXuat(){
        
        if (Auth.isLogin()) {
            new dangNhapJDialog(this,true).setVisible(true);
        }
        else{
            MgsBox.alert(this,"Vui lòng Đăng nhập!");
        }
        
    }
    void ketThuc(){
       if(MgsBox.confirm(this, "Bạn có muốn thoát khỏi ứng dụng không?")){
        System.exit(0);
         }
    }
    void openNhanvien(){
        if (Auth.isLogin()) {
            new NhanvienJDialog(this,true).setVisible(true);
        }
        else{
            MgsBox.alert(this,"Vui lòng Đăng nhập!");
        }
        
    }
    void openKHoaHoc(){
        if (Auth.isLogin()) {
            new KhoaHocJDiaLog(this,true).setVisible(true);
        }
        else{
            MgsBox.alert(this,"Vui lòng Đăng nhập!");
        }
        
    }
    void openChuyenDe(){
        if (Auth.isLogin()) {
            new ChuyenDeJDiaLog(this,true).setVisible(true);
        }
        else{
            MgsBox.alert(this,"Vui lòng Đăng nhập!");
        }
        
    }
    void openNguoiHoc(){
        if (Auth.isLogin()) {
            new NguoiHocJDiaLog(this,true).setVisible(true);
        }
        else{
            MgsBox.alert(this,"Vui lòng Đăng nhập!");
        }
        
    }
    void openHocVien(){
        if (Auth.isLogin()) {
            new HocvienDiaLog(this,true).setVisible(true);
        }
        else{
            MgsBox.alert(this,"Vui lòng Đăng nhập!");
        }
        
    } 
   
    void openThongKe(int index) {            
        if (Auth.isLogin()) {
            if (index==3&&!Auth.isManager()) {
               MgsBox.alert(this,"Bạn không được xem doanh thu");
            }
            else{
                thongKejDialog tkwin =new thongKejDialog(index);
                tkwin.setVisible(true);
                tkwin.setselectTab(index);
            }    
        } else {
            MgsBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    
    void openGioiThieu(){
        new gioiThieuJDialog(this,true).setVisible(true);
        
    }
    void openHuongDan(){
        try {
            Desktop.getDesktop().browse(new File("help/index.html").toURI());
        } catch (Exception e) {
            MgsBox.alert(this,"Khong tim thay file huong dan");
        }
    }
    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here: 
       
        dangXuat();
         Auth.clear();
        
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniketthucActionPerformed
        // TODO add your handling code here:
        ketThuc();
        
    }//GEN-LAST:event_mniketthucActionPerformed
    
    private void mniChuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChuyendeActionPerformed
        // TODO add your handling code here:
        openChuyenDe();
       
    }//GEN-LAST:event_mniChuyendeActionPerformed

    private void mniDiemchuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiemchuyendeActionPerformed
        // TODO add your handling code here:
        openThongKe(2);
    }//GEN-LAST:event_mniDiemchuyendeActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        
        dangXuat();
        Auth.clear();
        
    }//GEN-LAST:event_btnDangXuatActionPerformed
    
    private void mniNguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNguoihocActionPerformed
        // TODO add your handling code here:
        openNguoiHoc();
        
    }//GEN-LAST:event_mniNguoihocActionPerformed

    private void mnidangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangnhapActionPerformed
        // TODO add your handling code here:
        dangNhap();
        
    }//GEN-LAST:event_mnidangnhapActionPerformed
    
    private void MnikhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnikhoahocActionPerformed
        // TODO add your handling code here:
        openKHoaHoc();
        
    }//GEN-LAST:event_MnikhoahocActionPerformed
    
    private void mniNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanvienActionPerformed
        // TODO add your handling code here:
        openNhanvien();
       
    }//GEN-LAST:event_mniNhanvienActionPerformed

    private void btnKetthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetthucActionPerformed
        // TODO add your handling code here:
        ketThuc();
       
    }//GEN-LAST:event_btnKetthucActionPerformed

    private void btnChuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyendeActionPerformed
        // TODO add your handling code here:
        openChuyenDe();
        
    }//GEN-LAST:event_btnChuyendeActionPerformed

    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
        // TODO add your handling code here:
        openNguoiHoc();
        
    }//GEN-LAST:event_btnNguoiHocActionPerformed

    private void btnKhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoahocActionPerformed
        // TODO add your handling code here:
        openKHoaHoc();
       
    }//GEN-LAST:event_btnKhoahocActionPerformed
    
    private void mniluongnguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniluongnguoihocActionPerformed
        // TODO add your handling code here:
        openThongKe(0);
        
    }//GEN-LAST:event_mniluongnguoihocActionPerformed

    private void btnHuongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongdanActionPerformed
        // TODO add your handling code here:
        openHuongDan();
        
    }//GEN-LAST:event_btnHuongdanActionPerformed

    private void mniBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBangDiemActionPerformed
        // TODO add your handling code here:
        openThongKe(1);
        
    }//GEN-LAST:event_mniBangDiemActionPerformed

    private void MniDoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniDoanhthuActionPerformed
        // TODO add your handling code here:
        openThongKe(3);
        
    }//GEN-LAST:event_MniDoanhthuActionPerformed
    
    private void mniGioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioithieuActionPerformed
        // TODO add your handling code here:
        openGioiThieu();
        
    }//GEN-LAST:event_mniGioithieuActionPerformed

    private void mnihuongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnihuongdanActionPerformed
        // TODO add your handling code here:
        openHuongDan();
        
    }//GEN-LAST:event_mnihuongdanActionPerformed

    private void mnidoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidoimkActionPerformed
        // TODO add your handling code here:
        openDoiMatKhau();
    }//GEN-LAST:event_mnidoimkActionPerformed

    private void jdesktopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdesktopMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jdesktopMouseReleased

    private void mnihocvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnihocvienActionPerformed
        // TODO add your handling code here:
        openHocVien();
    }//GEN-LAST:event_mnihocvienActionPerformed

    private void btnHocvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocvienActionPerformed
        // TODO add your handling code here:
        openHocVien();
    }//GEN-LAST:event_btnHocvienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MniDoanhthu;
    private javax.swing.JMenuItem Mnikhoahoc;
    private javax.swing.JButton btnChuyende;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHocvien;
    private javax.swing.JButton btnHuongdan;
    private javax.swing.JButton btnKetthuc;
    private javax.swing.JButton btnKhoahoc;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane jdesktop;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lbltrangthai;
    private javax.swing.JMenuItem mniBangDiem;
    private javax.swing.JMenuItem mniChuyende;
    private javax.swing.JMenu mniDangNhap;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDiemchuyende;
    private javax.swing.JMenuItem mniGioithieu;
    private javax.swing.JMenuItem mniNguoihoc;
    private javax.swing.JMenuItem mniNhanvien;
    private javax.swing.JMenuItem mnidangnhap;
    private javax.swing.JMenuItem mnidoimk;
    private javax.swing.JMenuItem mnihocvien;
    private javax.swing.JMenuItem mnihuongdan;
    private javax.swing.JMenuItem mniketthuc;
    private javax.swing.JMenuItem mniluongnguoihoc;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
